In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import numpy as np
import pandas as pd

# shark_attack_url = "https://docs.google.com/spreadsheets/d/18FsaiIPwdWPjY9wkeLwSOJGBUe0f-oKL/edit?usp=sharing&ouid=115737411907616007195&rtpof=true&sd=true"
shark_attack_url = "/content/drive/MyDrive/GSAF5.xlsx"
pd.read_excel(shark_attack_url) # /content/drive/MyDrive/GSAF5.xlsx

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
0,May-5-1803,1803.0,Unprovoked,JAVA,Orange Point,NaN,Swimming,John Walker,M,13,...,Undetermined,Tales of Travellers a view of the world Octobe...,1803.05.17-Jones.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1803.05.17,1803.05.17,181.0,NaN,NaN
1,26-Dec-1860,1860.0,Unprovoked,AUSTRALIA,New South Wales,"The Domain, Sydney",Bathing,NaN,M,NaN,...,NaN,"The Argus, 12/31/1860",1860.12.26-TheDomain-Sydney.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1860.12.26,1860.12.26,329.0,NaN,NaN
2,Oct-1860,1860.0,Sea Disaster,CANADA,Nova Scotia,Cape Canso,Gloucester fishing schooner run down,2 males,M,NaN,...,NaN,"Baltimore Sun, 10/1/1860",1860.10.00-Gloucester.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1860.10.00,1860.10.00,328.0,NaN,NaN
3,01-Aug-1860,1860.0,Unprovoked,USA,New York,Brooklyn,Swimming,Jerry Duke,M,NaN,...,NaN,"New York Times, 8/3/1860; Brooklyn News, 8/3/1...",1860.08.01-JerryDuke.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1860.08.01,1860.08.01,327.0,NaN,NaN
4,Apr-1860,1860.0,Unprovoked,NEW ZEALAND,North Island,"Princes Wharf, Auckland Harbor",Swimming,H. Cook,M,NaN,...,NaN,P.Tichener,1860.04.00.b-Cook.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1860.04.00.b,1860.04.00.b,326.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7120,8th January,2026.0,Unprovoked,US Virgin Islands,Fredricksted Island St Croix,Dorsch Beach,Snorkeling,Arlene Lillis,F,56,...,Unknown,Todd Smith: KevinMcMurray Trackingsharks.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7121,5th January,2026.0,Unprovoked,Mozambique,Inhambe Province,Vilanculous District,Diving,Unknown,M,?,...,Unknown,Kevin McMurray Trackingsharks.com : Macao News:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7122,3rd January,2026.0,Provoked,New Caledonia,Kélé,Between Bourail and Moindou,Scuba Diving,Unknown,M,?,...,Unknown,Andy Currie: Province Sud:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7123,Reported 08-Jan-2017,NaN,Invalid,AUSTRALIA,Queensland,NaN,Spearfishing,Kerry Daniel,M,35,...,Bull shark,Liquid Vision 1/8/2017,2017.01.08.R-KerryDaniel.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.01.08.R,2017.01.08.R,6142.0,NaN,NaN
7124,Reported 19-Aug-1836,NaN,Unprovoked,ENGLAND,Cumberland,Whitehaven,Swimming,a boy,M,NaN,...,NaN,"C. Moore, GSAF",1835.08.19.R-Whitehaven.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1836.08.19.R,1836.08.19.R,230.0,NaN,NaN

In [ ]:
# Renaming the variable and displaying the DataFrame

shark_attack_filtered = pd.read_excel(shark_attack_url)
display(shark_attack_filtered.head())

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
0,May-5-1803,1803.0,Unprovoked,JAVA,Orange Point,NaN,Swimming,John Walker,M,13,...,Undetermined,Tales of Travellers a view of the world Octobe...,1803.05.17-Jones.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1803.05.17,1803.05.17,181.0,NaN,NaN
1,26-Dec-1860,1860.0,Unprovoked,AUSTRALIA,New South Wales,"The Domain, Sydney",Bathing,NaN,M,NaN,...,NaN,"The Argus, 12/31/1860",1860.12.26-TheDomain-Sydney.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1860.12.26,1860.12.26,329.0,NaN,NaN
2,Oct-1860,1860.0,Sea Disaster,CANADA,Nova Scotia,Cape Canso,Gloucester fishing schooner run down,2 males,M,NaN,...,NaN,"Baltimore Sun, 10/1/1860",1860.10.00-Gloucester.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1860.10.00,1860.10.00,328.0,NaN,NaN
3,01-Aug-1860,1860.0,Unprovoked,USA,New York,Brooklyn,Swimming,Jerry Duke,M,NaN,...,NaN,"New York Times, 8/3/1860; Brooklyn News, 8/3/1...",1860.08.01-JerryDuke.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1860.08.01,1860.08.01,327.0,NaN,NaN
4,Apr-1860,1860.0,Unprovoked,NEW ZEALAND,North Island,"Princes Wharf, Auckland Harbor",Swimming,H. Cook,M,NaN,...,NaN,P.Tichener,1860.04.00.b-Cook.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1860.04.00.b,1860.04.00.b,326.0,NaN,NaN

In [ ]:
# Cleaning column names

shark_attack_df.columns = (
    shark_attack_df.columns
    .str.strip()
    .str.lower()
    .str.replace(" y/n", "")
    .str.replace(" ", "_")

)

# Check the data type for each column

shark_attack_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7125 entries, 0 to 7124
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            7125 non-null   object
 1   year            7123 non-null   Int64
 2   type            7107 non-null   object
 3   country         7075 non-null   object
 4   state           6638 non-null   object
 5   location        6558 non-null   object
 6   activity        6542 non-null   object
 7   name            6907 non-null   object
 8   sex             6547 non-null   object
 9   age             3952 non-null   Int64
 10  injury          7089 non-null   object
 11  fatal           6564 non-null   object
 12  time            3598 non-null   object
 13  species         3994 non-null   object
 14  source          7105 non-null   object
 15  pdf             6799 non-null   object
 16  href_formula    6794 non-null   object
 17  href            6796 non-null   object
 18  case_number     6798 non-null   object
 19  case_number.1   6797 non-null   object
 20  original_order  6799 non-null   float64
 21  unnamed:_21     1 non-null      object
 22  unnamed:_22     2 non-null      object
dtypes: Int64(2), float64(1), object(20)
memory usage: 1.3+ MB

In [ ]:
# Change data type for column "year"

shark_attack_df["year"] = shark_attack_df["year"].astype("Int64")

In [ ]:
# Change data type for age

shark_attack_df["age"]= pd.to_numeric(shark_attack_df["age"], errors="coerce")

shark_attack_df["age"] = shark_attack_df["age"].astype("Int64")

In [ ]:
# Remove records with empty source (we assume this record can't be proved, therefore, it shouldn't be taken into account)

records_without_source = shark_attack_df.dropna(subset=["source"])
records_without_source.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7105 entries, 0 to 7124
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            7105 non-null   object
 1   year            7103 non-null   Int64
 2   type            7088 non-null   object
 3   country         7055 non-null   object
 4   state           6620 non-null   object
 5   location        6539 non-null   object
 6   activity        6527 non-null   object
 7   name            6888 non-null   object
 8   sex             6529 non-null   object
 9   age             3944 non-null   Int64
 10  injury          7070 non-null   object
 11  fatal           6549 non-null   object
 12  time            3590 non-null   object
 13  species         3982 non-null   object
 14  source          7105 non-null   object
 15  pdf             6779 non-null   object
 16  href_formula    6774 non-null   object
 17  href            6776 non-null   object
 18  case_number     6778 non-null   object
 19  case_number.1   6777 non-null   object
 20  original_order  6779 non-null   float64
 21  unnamed:_21     1 non-null      object
 22  unnamed:_22     2 non-null      object
dtypes: Int64(2), float64(1), object(20)
memory usage: 1.3+ MB

In [ ]:
# Checking if we have duplicated rows
duplicated_records = records_without_source.duplicated().sum()
print(duplicated_records)

0

In [ ]:
# Remove time, species & source columns
refined_dataset = records_without_source.drop(columns=["time", "species", "source"])
refined_dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7105 entries, 0 to 7124
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            7105 non-null   object
 1   year            7103 non-null   Int64
 2   type            7088 non-null   object
 3   country         7055 non-null   object
 4   state           6620 non-null   object
 5   location        6539 non-null   object
 6   activity        6527 non-null   object
 7   name            6888 non-null   object
 8   sex             6529 non-null   object
 9   age             3944 non-null   Int64
 10  injury          7070 non-null   object
 11  fatal           6549 non-null   object
 12  pdf             6779 non-null   object
 13  href_formula    6774 non-null   object
 14  href            6776 non-null   object
 15  case_number     6778 non-null   object
 16  case_number.1   6777 non-null   object
 17  original_order  6779 non-null   float64
 18  unnamed:_21     1 non-null      object
 19  unnamed:_22     2 non-null      object
dtypes: Int64(2), float64(1), object(17)
memory usage: 1.2+ MB

In [ ]:
#Reset the indexes

refined_dataset = refined_dataset.reset_index(drop=True)

In [ ]:
# Does it make sense to change fatal to boolean (true/false)?

----- DATE -----

In [ ]:
# First 15 element in the date, to see the pattern:

print(refined_dataset['date'][:15])

0               May-5-1803
1              26-Dec-1860
2                 Oct-1860
3              01-Aug-1860
4                 Apr-1860
5                 Apr-1860
6              27-Mar-1860
7              11-Mar-1860
8              10-Nov-1861
9     Reported 25-Sep-1861
10                Mar-1861
11    Reported 12-Feb-1861
12    Reported 15-Jan-1861
13             14-Nov-2010
14             26-Dec-2015
Name: date, dtype: object

In [ ]:
import re

# 1. First, try to parse dates using pandas to_datetime (handles standard formats like 2025-06-11)
parsed_dates = pd.to_datetime(refined_dataset['date'], errors='coerce')

# Extract month name from successfully parsed datetime objects
refined_dataset['month'] = parsed_dates.dt.month_name()

# 2. For rows where pandas couldn't parse it (e.g., "20th October", historical dates), use regex fallback
months_list = ['January', 'February', 'March', 'April', 'May', 'June',
               'July', 'August', 'September', 'October', 'November', 'December',
               'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
               ]
pattern = '|'.join(months_list)

# Fill missing months using regex extraction on the original text
mask_missing = refined_dataset['month'].isnull()
refined_dataset.loc[mask_missing, 'month'] = (
    refined_dataset.loc[mask_missing, 'date']
    .str.extract(f'({pattern})', flags=re.IGNORECASE)[0]
)

# Check how many rows are still without a month
missing_months = refined_dataset['month'].isnull().sum()
print(f"Number of rows without a month: {missing_months}")

# Show some examples of what is still missing (truly historical or irregular entries)
print("\nExamples of remaining missing dates:")
print(refined_dataset[refined_dataset['month'].isnull()]['date'].head(10))

# Check the distribution of the newly populated month column
print("\nMonth distribution:")
print(refined_dataset['month'].value_counts())

Number of rows without a month: 527

Examples of remaining missing dates:
293       2017.06.05
938     Ca. 214 B.C.
939    Ca. 336.B.C..
940     Ca. 493 B.C.
941     Ca. 725 B.C.
942    Ca. 1010  BC
943       Ca 4000 BC
944    Prior to 1988
945       After 2013
946      Before 1824
Name: date, dtype: object

Month distribution:
month
Jul          763
Aug          663
Sep          605
Jan          567
Jun          540
Oct          498
Dec          488
Apr          487
May          468
Mar          455
Nov          451
Feb          418
July          36
June          24
January       18
August        15
September     14
April         14
December      12
November      12
March         11
February      10
October        9
Name: count, dtype: int64

In [ ]:
# Map short month names to full names to clean up the distribution
month_mapping = {
    'Jan': 'January', 'Feb': 'February', 'Mar': 'March', 'Apr': 'April',
    'May': 'May', 'Jun': 'June', 'Jul': 'July', 'Aug': 'August',
    'Sep': 'September', 'Oct': 'October', 'Nov': 'November', 'Dec': 'December'
}

# Apply mapping (we can capitalize the first 3 letters to match the keys safely)
refined_dataset['month'] = refined_dataset['month'].replace(month_mapping)

# Check the final, clean month distribution
print("Cleaned and unified Month distribution:")
print(refined_dataset['month'].value_counts())

Cleaned and unified Month distribution:
month
July         799
August       678
September    619
January      585
June         564
October      507
April        501
December     500
May          468
March        466
November     463
February     428
Name: count, dtype: int64

In [ ]:
# Check in how many rows we did not find a month.
missing_months = refined_dataset['month'].isnull().sum()
print(f"Number of rows without a month: {missing_months}")

# Show a few examples where the month became NaN.
print(refined_dataset[refined_dataset['month'].isnull()]['date'].head(10))

Number of rows without a month: 527
293       2017.06.05
938     Ca. 214 B.C.
939    Ca. 336.B.C..
940     Ca. 493 B.C.
941     Ca. 725 B.C.
942    Ca. 1010  BC
943       Ca 4000 BC
944    Prior to 1988
945       After 2013
946      Before 1824
Name: date, dtype: object

----- YEAR -----

In [ ]:
shark_attack_filtered = refined_dataset[(refined_dataset["year"] >= 2000) & (refined_dataset["year"] <= 2026)]
shark_attack_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2863 entries, 13 to 7102
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            2863 non-null   object
 1   year            2863 non-null   Int64
 2   type            2850 non-null   object
 3   country         2861 non-null   object
 4   state           2744 non-null   object
 5   location        2755 non-null   object
 6   activity        2740 non-null   object
 7   name            2821 non-null   object
 8   sex             2745 non-null   object
 9   age             2077 non-null   Int64
 10  injury          2854 non-null   object
 11  fatal           2684 non-null   object
 12  pdf             2542 non-null   object
 13  href_formula    2539 non-null   object
 14  href            2539 non-null   object
 15  case_number     2541 non-null   object
 16  case_number.1   2540 non-null   object
 17  original_order  2542 non-null   float64
 18  unnamed:_21     1 non-null      object
 19  unnamed:_22     0 non-null      object
 20  month           2853 non-null   object
dtypes: Int64(2), float64(1), object(18)
memory usage: 497.7+ KB

In [ ]:
# 1. Check minimum and maximum years
print("Min year:", shark_attack_filtered['year'].min())
print("Max year:", shark_attack_filtered['year'].max())

# 2. Count missing (NaN) years
print("Missing years count:", shark_attack_filtered['year'].isnull().sum())

# 3. List the earliest years in the dataset to check for anomalies
print("\nEarliest years in dataset:")
print(shark_attack_filtered['year'].value_counts().sort_index().head(15))

# 4. List the latest years in the dataset to check for future dates or typos
print("\nLatest years in dataset:")
print(shark_attack_filtered['year'].value_counts().sort_index().tail(15))

# Check all unique years sorted in ascending order to spot any weird values
unique_years = sorted(shark_attack_filtered['year'].dropna().unique())
print("Unique years in dataset:", unique_years)

Min year: 2000
Max year: 2026
Missing years count: 0

Earliest years in dataset:
year
2000     97
2001     92
2002     88
2003     92
2004     92
2005    103
2006    103
2007    113
2008    121
2009    119
2010    101
2011    128
2012    117
2013    121
2014    126
Name: count, dtype: Int64

Latest years in dataset:
year
2012    117
2013    121
2014    126
2015    142
2016    132
2017    140
2018    123
2019    114
2020    101
2021    110
2022     97
2023    109
2024     52
2025     69
2026     61
Name: count, dtype: Int64
Unique years in dataset: [np.int64(2000), np.int64(2001), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024), np.int64(2025), np.int64(2026)]

In [ ]:
# Check how many entries have years before 1900 or equal to 0/5
invalid_or_ancient = shark_attack_filtered[shark_attack_filtered['year'] < 1900]
print(f"Number of rows with year < 1900 (or invalid): {len(invalid_or_ancient)}")
print(invalid_or_ancient['year'].value_counts().sort_index())

Number of rows with year < 1900 (or invalid): 0
Series([], Name: count, dtype: Int64)

----- COUNTRY -----

In [ ]:

# Check the top 10 countries by attack frequency
if 'country' in refined_dataset.columns:
    print("\nTop 10 countries:")
    print(refined_dataset['country'].value_counts().head(10))

# Check missing values in the country column
print("\nMissing countries count:", shark_attack_filtered['country'].isnull().sum())

# Check total number of unique countries (to see if there are formatting inconsistencies)
print("\nTotal unique countries (raw):", shark_attack_filtered['country'].nunique())

Top 10 countries:
country
USA                 2590
AUSTRALIA           1479
SOUTH AFRICA         595
NEW ZEALAND          143
PAPUA NEW GUINEA     136
BAHAMAS              135
BRAZIL               122
MEXICO               103
ITALY                 72
FIJI                  67
Name: count, dtype: int64

Missing countries count: 2

Total unique countries (raw): 147

In [ ]:
# Clean the country column: strip whitespaces and convert to uppercase for uniformity
shark_attack_filtered['country'] = shark_attack_filtered['country'].str.strip().str.upper()

# Check unique countries after basic cleaning
print("Unique countries after basic cleaning:", shark_attack_filtered['country'].nunique())

# Display the least frequent countries to check for remaining typos or weird strings
print("\nLeast frequent countries after basic cleaning:")
print(shark_attack_filtered['country'].value_counts().tail(15))

Unique countries after basic cleaning: 113

Least frequent countries after basic cleaning:
country
ANTIGUA                    1
CHILE                      1
SAUDI ARABIA               1
DIEGO GARCIA               1
PALESTINIAN TERRITORIES    1
GREECE                     1
KIRIBATI                   1
ST. MARTIN                 1
CORAL SEA                  1
PORTUGAL                   1
ARGENTINA                  1
TRINIDAD                   1
CANARY ISLANDS             1
GALAPOGOS ISLANDS          1
US VIRGIN ISLANDS          1
Name: count, dtype: int64

/tmp/ipykernel_547/537217864.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  shark_attack_filtered['country'] = shark_attack_filtered['country'].str.strip().str.upper()

In [ ]:
country_counts = shark_attack_filtered['country'].value_counts()

# 1. Number of unique country names that appear only once
unique_single_count = (country_counts == 1).sum()
print(f"Number of unique countries appearing only once: {unique_single_count}")

# 2. Total number of rows belonging to these single-occurrence countries
total_rows_single = shark_attack_filtered['country'].map(country_counts == 1).sum()
print(f"Total rows affected by these countries: {total_rows_single}")

Number of unique countries appearing only once: 43
Total rows affected by these countries: 43

In [ ]:
# Create a dictionary to map historical names or clean specific inconsistencies
# You can add more mappings here if you find other historical names
country_mapping = {
    'CEYLON (SRI LANKA)': 'SRI LANKA',
    'NEW GUINEA': 'PAPUA NEW GUINEA',
    'TASMAN SEA': 'OPEN WATER',
    'RED SEA?': 'OPEN WATER',
    'ASIA?': 'OPEN WATER',
    'AFRICA': 'OPEN WATER',
    'COAST OF AFRICA': 'OPEN WATER',
    'BETWEEN PORTUGAL & INDIA': 'OPEN WATER',
    'ROATAN': 'OPEN WATER',
    'OCEAN': 'OPEN WATER',
    'PACIFIC OCEAN': 'OPEN WATER',
    'INDIAN OCEAN?': 'OPEN WATER',
    'INDIAN OCEAN': 'OPEN WATER',
    'PACIFIC OCEAN?': 'OPEN WATER',
    'SUDAN?':'SUDAN',
    'UNITED ARAB EMIRATES (UAE)':'UNITED ARAB EMIRATES',
    'RED SEA / INDIAN OCEAN':'OPEN WATER',
    'MID-PACIFC OCEAN': 'OPEN WATER',
    'MID ATLANTIC OCEAN': 'OPEN WATER',
    'ATLANTIC OCEAN': 'OPEN WATER',
    'NORTH PACIFIC OCEAN': 'OPEN WATER',
    'SOUTH ATLANTIC OCEAN': 'OPEN WATER',
    'NORTH ATLANTIC OCEAN': 'OPEN WATER',
    'SOUTH PACIFIC OCEAN': 'OPEN WATER',
    'SOUTHWEST PACIFIC OCEAN': 'OPEN WATER',


}


# Apply the mapping
shark_attack_filtered['country'] = shark_attack_filtered['country'].replace(country_mapping)


# Check unique countries after basic cleaning
print("\nUnique countries after basic cleaning:", shark_attack_filtered['country'].nunique())

# Display the least frequent countries to check for remaining typos or weird strings
print("\nLeast frequent countries after basic cleaning:")
print(shark_attack_filtered['country'].value_counts().tail(30))

Unique countries after basic cleaning: 112

Least frequent countries after basic cleaning:
country
GULF OF ADEN               1
LIBERIA                    1
ST. MAARTIN                1
GRAND CAYMAN               1
SRI LANKA                  1
URUGUAY                    1
OKINAWA                    1
MOROCCO                    1
SOMALIA                    1
NORWAY                     1
NEVIS                      1
MALTA                      1
SENEGAL                    1
YEMEN                      1
NIGERIA                    1
ANTIGUA                    1
CHILE                      1
SAUDI ARABIA               1
DIEGO GARCIA               1
PALESTINIAN TERRITORIES    1
GREECE                     1
KIRIBATI                   1
ST. MARTIN                 1
CORAL SEA                  1
PORTUGAL                   1
ARGENTINA                  1
TRINIDAD                   1
CANARY ISLANDS             1
GALAPOGOS ISLANDS          1
US VIRGIN ISLANDS          1
Name: count, dtype: int64

/tmp/ipykernel_547/1402782002.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  shark_attack_filtered['country'] = shark_attack_filtered['country'].replace(country_mapping)

In [ ]:
# Countries with special char
special_chars_countries = shark_attack_filtered[shark_attack_filtered['country'].str.contains(r'[^A-Z\s]', na=False)]['country'].unique()
print("Countries with special characters or punctuation left:", special_chars_countries)

Countries with special characters or punctuation left: ['ST HELENA, BRITISH OVERSEAS TERRITORY' 'ST KITTS / NEVIS'
 'TURKS & CAICOS' 'ST. MAARTIN' 'TRINIDAD & TOBAGO' 'ST. MARTIN']

----------SEX------------------------------------

In [ ]:

display(shark_attack_filtered["sex"].unique())
print("Number of distinct values:", shark_attack_filtered["sex"].nunique())

array(['M', 'F', nan, 'LLI', '?', 'M F'], dtype=object)

Number of distinct values: 5

In [ ]:
shark_attack_filtered["sex"].value_counts(dropna=False)

sex
M      2222
F       520
NaN     118
LLI       1
?         1
M F       1
Name: count, dtype: int64

In [ ]:
shark_attack_filtered["sex"] =(
    shark_attack_filtered["sex"]
        .str.strip()
        .str.upper()
)
shark_attack_filtered["sex"].value_counts(dropna=False)

/tmp/ipykernel_547/1925377618.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  shark_attack_filtered["sex"] =(

sex
M      2219
F       520
NaN     121
LLI       1
?         1
M F       1
Name: count, dtype: int64

In [ ]:
shark_attack_filtered["sex"] = (shark_attack_filtered["sex"]
    .replace({"m": "M"}))

/tmp/ipykernel_547/2545713766.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  shark_attack_filtered["sex"] = (shark_attack_filtered["sex"]

In [ ]:
print(shark_attack_filtered["sex"].unique())
print("Number of distinct values:", shark_attack_filtered["sex"].nunique())
print("Missing values:", shark_attack_filtered["sex"].isna().sum())
print("Total rows:", len(shark_attack_filtered))

['M' 'F' nan 'LLI' '?' 'M F']
Number of distinct values: 5
Missing values: 121
Total rows: 2863

---- PROVOKED / UNPROVOKED ---

In [ ]:
print(shark_attack_filtered['type'].unique())
print(shark_attack_filtered['type'].nunique())

['Unprovoked' 'Watercraft' 'Invalid' 'Provoked' 'Sea Disaster' nan
 'Questionable' 'Under investigation' 'Unconfirmed' 'Unverified' '?'
 ' Provoked' 'unprovoked' 'UNprovoked']
13

In [ ]:
type_mapping = {
    'unprovoked':'Unprovoked',
    'UNprovoked':'Unprovoked',
    ' Provoked':'Provoked',
    'Watercraft':'Unprovoked',
    'Invalid':'Unverified',
    'Sea Disaster':'Unprovoked',
    'Questionable':'Unverified',
    'Under investigation':'Unverified',
    'Unconfirmed':'Unverified',
    '?':'Unverified',


}

# Apply the mapping
shark_attack_filtered['type'] = shark_attack_filtered['type'].replace(type_mapping)


# Check unique countries after basic cleaning
print("\nUnique countries after basic cleaning:", shark_attack_filtered['type'].nunique())

# Display the least frequent countries to check for remaining typos or weird strings
print("\nLeast frequent countries after basic cleaning:")
print(shark_attack_filtered['type'].value_counts().tail(30))

Unique countries after basic cleaning: 3

Least frequent countries after basic cleaning:
type
Unprovoked    2411
Provoked       232
Unverified     207
Name: count, dtype: int64

/tmp/ipykernel_547/2378823162.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  shark_attack_filtered['type'] = shark_attack_filtered['type'].replace(type_mapping)

In [ ]:
shark_attack_filtered['type'] = shark_attack_filtered['type'].fillna('Unverified')

print(shark_attack_filtered['type'].value_counts(dropna=False))

type
Unprovoked    2411
Provoked       232
Unverified     220
Name: count, dtype: int64

/tmp/ipykernel_547/2353314399.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  shark_attack_filtered['type'] = shark_attack_filtered['type'].fillna('Unverified')

In [ ]:
# Check the top 10 countries by attack frequency
if 'country' in refined_dataset.columns:
    print("\nTop 10 countries:")
    print(shark_attack_filtered['country'].value_counts().head(10))

# Check missing values in the country column
print("\nMissing countries count:", shark_attack_filtered['country'].isnull().sum())

# Check total number of unique countries (to see if there are formatting inconsistencies)
print("\nTotal unique countries (raw):", shark_attack_filtered['country'].nunique())

Top 10 countries:
country
USA                 1365
AUSTRALIA            588
SOUTH AFRICA         156
BAHAMAS               89
BRAZIL                69
NEW ZEALAND           60
MEXICO                42
NEW CALEDONIA         41
EGYPT                 34
FRENCH POLYNESIA      32
Name: count, dtype: int64

Missing countries count: 2

Total unique countries (raw): 112

In [ ]:
shark_attack_filtered['type'] = shark_attack_filtered['type'].fillna('Unverified')

print(shark_attack_filtered['type'].value_counts(dropna=False))

type
Unprovoked    2411
Provoked       232
Unverified     220
Name: count, dtype: int64

/tmp/ipykernel_547/2353314399.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  shark_attack_filtered['type'] = shark_attack_filtered['type'].fillna('Unverified')

In [ ]:
print(shark_attack_filtered['sex'].value_counts())

contingency_table = pd.crosstab(
    shark_attack_filtered['type'],
    shark_attack_filtered['sex'],
    normalize='index')

display(contingency_table)


contingency_table = pd.crosstab(
    shark_attack_filtered['sex'],
    shark_attack_filtered['type'],
    normalize='index')

display(contingency_table)

sex
M      2219
F       520
LLI       1
?         1
M F       1
Name: count, dtype: int64

sex                ?         F       LLI         M       M F
type
Provoked    0.000000  0.207965  0.000000  0.792035  0.000000
Unprovoked  0.000434  0.187419  0.000434  0.811280  0.000434
Unverified  0.000000  0.194313  0.000000  0.805687  0.000000

type  Provoked  Unprovoked  Unverified
sex
?     0.000000    1.000000    0.000000
F     0.090385    0.830769    0.078846
LLI   0.000000    1.000000    0.000000
M     0.080667    0.842722    0.076611
M F   0.000000    1.000000    0.000000

In [ ]:
import sys
print(sys.version)

3.13.16 (main, Oct  1 2026, 15:40:24) [GCC 13.3.0]